import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from './HomeStyles';

export { COLORS, FONTS };

export const ESTADO_TICKET_COLOR: Record<string, string> = {
    bot: COLORS.accent,
    escalado: COLORS.blue,
    resuelto: COLORS.green,
    cerrado: COLORS.muted,
};

export const ESTADO_TICKET_TEXTO: Record<string, string> = {
    bot: 'Con Boxy',
    escalado: 'Con el equipo',
    resuelto: 'Resuelta',
    cerrado: 'Cerrada',
};

export const styles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: COLORS.bg },
    flex: { flex: 1 },

    header: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingHorizontal: 18,
        paddingTop: 12,
        paddingBottom: 14,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border,
    },
    volver: {
        width: 38,
        height: 38,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: COLORS.border,
        backgroundColor: COLORS.surface,
        alignItems: 'center',
        justifyContent: 'center',
    },
    volverTexto: { color: COLORS.white, fontSize: 18, fontFamily: FONTS.titleBold },
    headerTextos: { flex: 1, minWidth: 0 },
    kicker: {
        color: COLORS.muted,
        fontSize: 11,
        letterSpacing: 0.6,
        textTransform: 'uppercase',
        fontFamily: FONTS.textMedium,
    },
    titulo: { color: COLORS.white, fontSize: 17, fontFamily: FONTS.titleBold },

    lista: { padding: 18, paddingBottom: 40, alignItems: 'center' },
    contenido: { width: '100%', maxWidth: 780 },

    bloqueTitulo: { color: COLORS.white, fontSize: 15, fontFamily: FONTS.titleBold, marginBottom: 6 },
    bloqueTexto: {
        color: COLORS.muted,
        fontSize: 13,
        lineHeight: 19,
        fontFamily: FONTS.text,
        marginBottom: 16,
    },

    preset: {
        backgroundColor: COLORS.surface,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: COLORS.border,
        paddingVertical: 15,
        paddingHorizontal: 16,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    presetTexto: { color: COLORS.white, fontSize: 14, fontFamily: FONTS.titleBold, flexShrink: 1 },
    presetFlecha: { color: COLORS.accent, fontSize: 16, fontFamily: FONTS.titleBold },

    ticketFila: {
        backgroundColor: COLORS.surface,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: COLORS.border,
        padding: 15,
        marginBottom: 10,
    },
    ticketTop: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
        marginBottom: 6,
    },
    ticketAsunto: { color: COLORS.white, fontSize: 14.5, fontFamily: FONTS.titleBold, flexShrink: 1 },
    ticketMeta: { color: COLORS.muted, fontSize: 12, fontFamily: FONTS.text },

    badge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingVertical: 6,
        paddingHorizontal: 11,
        borderRadius: 999,
    },
    badgePunto: { width: 7, height: 7, borderRadius: 999 },
    badgeTexto: { fontSize: 12, fontFamily: FONTS.titleBold },

    separador: { height: 26 },

    chat: { padding: 16, paddingBottom: 24 },
    burbujaFila: { flexDirection: 'row', marginBottom: 12 },
    burbujaFilaPropia: { justifyContent: 'flex-end' },
    burbuja: {
        maxWidth: '86%',
        borderRadius: 18,
        paddingVertical: 11,
        paddingHorizontal: 14,
        borderWidth: 1,
    },
    burbujaBot: { backgroundColor: COLORS.surface, borderColor: COLORS.border },
    burbujaAdmin: { backgroundColor: 'rgba(59, 130, 246, 0.12)', borderColor: 'rgba(59, 130, 246, 0.35)' },
    burbujaPropia: { backgroundColor: COLORS.accentSoft, borderColor: COLORS.borderAccent },
    autor: { fontSize: 11, fontFamily: FONTS.titleBold, marginBottom: 3 },
    autorBot: { color: COLORS.accent },
    autorAdmin: { color: COLORS.blue },
    mensajeTexto: { color: COLORS.white, fontSize: 14, lineHeight: 20, fontFamily: FONTS.text },
    hora: { color: 'rgba(255,255,255,0.38)', fontSize: 10.5, fontFamily: FONTS.text, marginTop: 4 },

    adjunto: {
        marginTop: 8,
        borderRadius: 12,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    adjuntoImagen: { width: '100%', height: 180, backgroundColor: COLORS.cardDeep },
    adjuntoArchivo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        padding: 11,
        backgroundColor: COLORS.cardDeep,
    },
    adjuntoNombre: { color: COLORS.white, fontSize: 13, fontFamily: FONTS.titleBold, flexShrink: 1 },
    adjuntoPeso: { color: COLORS.muted, fontSize: 11.5, fontFamily: FONTS.text },

    composer: {
        borderTopWidth: 1,
        borderTopColor: COLORS.border,
        padding: 12,
        backgroundColor: COLORS.bg,
        gap: 10,
    },
    adjuntoPreview: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
        backgroundColor: COLORS.surface,
        borderWidth: 1,
        borderColor: COLORS.borderAccent,
        borderRadius: 12,
        paddingVertical: 9,
        paddingHorizontal: 12,
    },
    quitar: { color: COLORS.muted, fontSize: 16, fontFamily: FONTS.titleBold, paddingHorizontal: 4 },

    composerFila: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
    entrada: {
        flex: 1,
        minHeight: 46,
        maxHeight: 120,
        backgroundColor: COLORS.surface,
        borderWidth: 1,
        borderColor: COLORS.borderStrong,
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingTop: 13,
        paddingBottom: 13,
        color: COLORS.white,
        fontSize: 14,
        fontFamily: FONTS.text,
    },
    botonIcono: {
        width: 46,
        height: 46,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: COLORS.borderStrong,
        backgroundColor: COLORS.surface,
        alignItems: 'center',
        justifyContent: 'center',
    },
    botonIconoTexto: { fontSize: 18, color: COLORS.white },
    enviar: { backgroundColor: COLORS.accent, borderColor: COLORS.accent },
    enviarTexto: { fontSize: 18, color: COLORS.ink, fontFamily: FONTS.titleBold },
    deshabilitado: { opacity: 0.45 },

    barraEstado: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingVertical: 9,
        paddingHorizontal: 14,
        backgroundColor: COLORS.surface,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border,
    },
    barraEstadoTexto: { color: COLORS.muted, fontSize: 12, fontFamily: FONTS.text, flexShrink: 1 },

    accionesFila: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 4 },
    botonTexto: {
        flexGrow: 1,
        minWidth: 140,
        paddingVertical: 12,
        borderRadius: 13,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: COLORS.borderStrong,
        backgroundColor: COLORS.card,
    },
    botonTextoTexto: { color: COLORS.white, fontSize: 13, fontFamily: FONTS.titleBold },

    centrado: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 },
    vacio: {
        color: COLORS.muted,
        fontSize: 13.5,
        fontFamily: FONTS.text,
        textAlign: 'center',
        lineHeight: 20,
    },
});
